# Generated by Django 3.2.5 on 2023-05-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=100)),
                ('product_url', models.URLField()),
                ('product_name', models.CharField(max_length=250)),
                ('current_price', models.IntegerField(default=100)),
            ],
        ),
    ]
