# Generated by Django 3.2.5 on 2023-05-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_wishlist_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
